### ISSUE TITLE
TypeError: context.parserServices.getStyleContext is not a function

### ISSUE THREAD

**Issue by marekdedic** [sveltejs/eslint-plugin-svelte#512]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

v8.43.0

### What version of `eslint-plugin-svelte` are you using?

2.31.0

### What did you do?

After updating to 2.31.0 (and I also do have `svelte-eslint-parser` v0.31.0, I checked), I enabled `no-unused-class-name` and got the following error :/

@ota-meshi Any ideas? I'm not that familiar with how the parser services get passed along...

### What did you expect to happen?

No error :)

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 8.43.0

TypeError: context.parserServices.getStyleContext is not a function
Occurred while linting /home/marekdedic/project/src/d.ts/CONFIG.d.ts:1
Rule: "svelte/no-unused-class-name"
    at Program:exit (/home/marekdedic/project/node_modules/eslint-plugin-svelte/lib/rules/no-unused-class-name.js:32:61)
    at ruleErrorHandler (/home/marekdedic/project/node_modules/eslint/lib/linter/linter.js:1050:28)
    at /home/marekdedic/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/marekdedic/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/marekdedic/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/marekdedic/project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.leaveNode (/home/marekdedic/project/node_modules/eslint/lib/linter/node-event-generator.js:349:14)
    at CodePathAnalyzer.leaveNode (/home/marekdedic/project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:816:23)
    at /home/marekdedic/project/node_modules/eslint/lib/linter/linter.js:1087:32
```

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/scout-handbook/handbook-web-admin/pull/217

**Comment by marekdedic** [comment]
Thanks for fixing my mistakes! :D
